### ISSUE TITLE
Align environment variables with wrangler

### ISSUE THREAD

**Issue by viraptor** [jacobbednarz/cf-vault#37]
Wrangler expects different variable names than cf-vault provides. Specifically (https://developers.cloudflare.com/workers/cli-wrangler/authentication#using-environment-variables)

```
You can deploy with authentication tokens (recommended). Obtain CF_ACCOUNT_ID and CF_API_TOKEN from the Cloudflare dashboard and run:

CF_ACCOUNT_ID=accountID CF_API_TOKEN=veryLongAPIToken wrangler publish

Or you can deploy with your email and your global API key. Obtain CF_EMAIL and CF_API_KEY from the Cloudflare dashboard and run:

CF_EMAIL=cloudflareEmail CF_API_KEY=veryLongAPI wrangler publish
```

It would be great if cf-vault exported those as well.

**Comment by jacobbednarz** [comment]
I'm 👍 to to exporting `CF_*` in _addition_ to the existing `CLOUDFLARE_*` environment variables but definitely can't do a full replacement as tools like Cloud foundry are already squatting on the `CF_*` space and have conflicts.
